package html;

import com.ccloomi.core.util.TemplateParserUtil;

/**© 2015-2016 CCLooMi.Inc Copyright
 * 类    名：TemplateParserTest
 * 类 描 述：
 * 作    者：Chenxj
 * 邮    箱：chenios@foxmail.com
 * 日    期：2016年4月5日-下午10:36:13
 */
public class TemplateParserTest {
	public static void main(String[] args) {
		String template="<html><head><title></title><meta><meta><meta><meta><meta><meta><meta></head><script></script><body><div><div><a></a></div></div><div><a><img></a><p><span></span></p></div><style></style><div><div><a><img></a><img><a><img></a><img><span></span></div></div><div><div><a><img></a><img><a><img></a><img><span>公司公告</span></div></div><div><div><h3></h3><table><tr><th>涉及概念</th><td><a>{tags}</td></tr><tr><th>公司名称</th><td>{name}</td></tr><tr><th>董&nbsp;事&nbsp;长</th><td>{chairman}</td></tr><tr><th>董&nbsp;&nbsp;&nbsp;秘</th><td>{secretaries}</td></tr><tr><th>主营业务</th><td>{mainbusiness}</td></tr><tr><th>实际控制人</th><td>{actualcontroller}</td></tr><tr><th>注册地址</th><td>{address}</td></tr><tr><th>上市日期</th><td>{listdate}</td></tr><tr><th>发行价/市盈率</th><td>{other}</td>";
		String html="<!DOCTYPE><html><head><title>北方导航(600435)-公司资料详细</title><meta><meta><meta><meta><meta><meta><meta></head><script></script><body><div><div><a>如何改进？F10诚邀您参与调查！</a></div></div><div><a><img></a><p><span>公司资料详细</span></p></div><style></style><div><div><a><img></a><img><a><img></a><img><span>新股频道</span></div></div><div><div><a><img></a><img><a><img></a><img><span>公司公告</span></div></div><div><div><h3>详细资料</h3><table><tr><th>涉及概念</th><td><a>央企国资改革、无人机、沪港通概念、融资融券、高端装备、军工</td></tr><tr><th>公司名称</th><td>北方导航控制技术股份有限公司</td></tr><tr><th>董&nbsp;事&nbsp;长</th><td>苏立航</td></tr><tr><th>董&nbsp;&nbsp;&nbsp;秘</th><td>赵晗</td></tr><tr><th>主营业务</th><td>军品和军民两用技术产品研发、生产和销售</td></tr><tr><th>实际控制人</th><td>国务院国有资产监督管理委员会</td></tr><tr><th>注册地址</th><td>北京市北京经济技术开发区科创十五街2号</td></tr><tr><th>上市日期</th><td>2003-07-04</td></tr><tr><th>发行价/市盈率</th><td>9.60元/19.2000倍</td></tr></table></div><script></script><div><h3>按行业<span>2015中报</span></h3><table><tr><th><span>主要指标</span></th><th>收入</th><th>成本</th></tr><tr><td><span>制造业</span></td><td>5.40亿</td><td>3.68亿</td></tr><tr><td><span>合计</span></td><td>5.40亿</td><td>3.68亿</td></tr></table><div><div><p>收入：</p><canvas></canvas></div><script></script><div><p><span></span>制造业</p></div></div></div><div><h3>按产品<span>2015中报</span></h3><table><tr><th><span>主要指标</span></th><th>收入</th><th>成本</th></tr><tr><td><span>军民两用产品</span></td><td>3.99亿</td><td>2.45亿</td></tr><tr><td><span>专用车产品</span></td><td>1.40亿</td><td>1.21亿</td></tr><tr><td><span>合计</span></td><td>5.40亿</td><td>3.67亿</td></tr></table><div><div><p>收入：</p><canvas></canvas></div><script></script><div><p><span></span>军民两用产品</p><p><span></span>专用车产品</p></div></div></div><div><h3>按地区<span>2015中报</span></h3><table><tr><th><span>主要指标</span></th><th>收入</th><th>成本</th></tr><tr><td><span>河南地区</span></td><td>1.87亿</td><td>--</td></tr><tr><td><span>北京地区</span></td><td>1.11亿</td><td>--</td></tr><tr><td><span>江苏地区</span></td><td>9668.01万</td><td>--</td></tr><tr><td><span>黑龙江地区</span></td><td>9009.71万</td><td>--</td></tr><tr><td><span>广东地区</span></td><td>5003.17万</td><td>--</td></tr><tr><td><span>衡阳地区</span></td><td>489.08万</td><td>--</td></tr><tr><td><span>合计</span></td><td>5.40亿</td><td>--</td></tr></table><div><div><p>收入：</p><canvas></canvas></div><script></script><div><p><span></span>河南地区</p><p><span></span>北京地区</p><p><span></span>江苏地区</p><p><span></span>其他收入之和</p></div></div></div><a><img></a></div><div><div></div><div></div><div></div><div><ul><li><a>财经</a></li><li><a>股票</a></li><li><a>新股</a></li><li><a>大盘</a></li><li><a>公司</a></li><li><a>名家</a></li><li><a>全球</a></li><li><a>基金</a></li><li><a>数据</a></li><li><a>学校</a></li><li><a>诊股</a></li><li><a>研报</a></li></ul><p>推荐</p><a>龙虎榜</a><a>投资日历</a><a>机会情报</a><a>智能选股</a></div></div><input><input><script></script><script></script><script></script><script></script><script></script><script></script></body></html>";
		System.out.println(TemplateParserUtil.parserHtmlTemplate2Map(html, template));
	}
}
